# Generated by Django 3.0.5 on 2020-04-20 01:44

from django.db import migrations, models
import django.db.models.deletion
import storage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='StoreFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_obj', models.FileField(blank=True, null=True, upload_to=storage.models.store_file_dir)),
                ('filename', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.IntegerField(blank=True, default=0, null=True)),
                ('storage_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_dt', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.Store')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
