# Generated by Django 3.0.5 on 2020-04-15 05:42

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefile',
            name='file_obj',
            field=models.FileField(blank=True, null=True, upload_to=storage.models.store_file_dir),
        ),
    ]
