# Generated by Django 3.0.5 on 2020-04-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storefile_file_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='storefile',
            name='upload_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
